from tech_template import TechTemplate

TECHS: dict[str, TechTemplate] = {
    'Archery': TechTemplate(
        name= 'Archery',
        cost= 25,
        unlocks_units= ['Archer'],
        advancement_level= 1,
    ),
    'Bronze Working': TechTemplate(
        name= 'Bronze Working',
        cost= 25,
        unlocks_units= ['Spearman'],
        advancement_level= 1,
    ),
    'Pottery': TechTemplate(
        name='Pottery',
        cost=20,
        unlocks_buildings=['Granary'],
        advancement_level=1,
    ),
    'Code of Laws': TechTemplate(
        name='Code of Laws',
        cost=20,
        unlocks_buildings=['Hanging Gardens'],
        advancement_level=1,
    ),
    'Calendar': TechTemplate(
        name='Calendar',
        cost=25,
        unlocks_buildings=['Temple of Artemis'],
        advancement_level=1,
    ),
    'The Wheel': TechTemplate(
        name='The Wheel',
        cost=35,
        unlocks_units=['Chariot'],
        unlocks_buildings=['Roads'],
        advancement_level=1,
    ),
    'Mining': TechTemplate(
        name='Mining',
        cost=30,
        unlocks_buildings=['Mine'],
        advancement_level=1,
    ),
    'Forestry': TechTemplate(
        name='Forestry',
        cost=25,
        advancement_level=1,
        unlocks_buildings=['Lumber Mill'],
    ),
    'Irrigation': TechTemplate(
        name='Irrigation',
        cost=25,
        unlocks_buildings=['Plantation', 'Husbandry Center'],
        advancement_level=1,
    ),
    'Writing': TechTemplate(
        name='Writing',
        cost=30,
        unlocks_buildings=['Library', 'Great Library'],
        advancement_level=1,
    ),
    'Masonry': TechTemplate(
        name='Masonry',
        cost=30,
        unlocks_units=['Garrison'],
        unlocks_buildings=['Pyramids'],
        advancement_level=1,
    ),
    'Mathematics': TechTemplate(
        name='Mathematics',
        cost=50,
        unlocks_units=['Catapult'],
        unlocks_buildings=['Workshop', 'Magisterium'],
        advancement_level=2,
    ),
    'Horseback Riding': TechTemplate(
        name='Horseback Riding',
        cost=50,
        unlocks_units=['Horseman', 'Horse Archer'],
        advancement_level=2,
    ),
    'Iron Working': TechTemplate(
        name='Iron Working',
        cost=45,
        unlocks_units=['Swordsman'],
        unlocks_buildings=['Colossus'],
        advancement_level=2,
    ),
    'Currency': TechTemplate(
        name='Currency',
        cost=40,
        unlocks_buildings=['Petra', 'Bazaar'],
        advancement_level=2,
    ),
    'Engineering': TechTemplate(
        name='Engineering',
        cost=45,
        unlocks_buildings=['Timberworks',  'Statue of Zeus'],
        advancement_level=2,
    ),
    'Construction': TechTemplate(
        name='Construction',
        cost=50,
        unlocks_buildings=['Aqueduct', 'Colosseum'],
        advancement_level=2,
    ),
    'Education': TechTemplate(
        name='Education',
        cost=55,
        unlocks_buildings=['University', 'National College'],
        advancement_level=3,
    ),
    'Machinery': TechTemplate(
        name='Machinery',
        cost=60,
        unlocks_units=[],
        unlocks_buildings=['Ironworks'],
        advancement_level=3,
    ),
    'Civil Service': TechTemplate(
        name='Civil Service',
        cost=60,
        unlocks_buildings=['Chichen Itza'],
        unlocks_units=['Pikeman'],
        advancement_level=3,
    ),
    'Chivalry': TechTemplate(
        name='Chivalry',
        cost=65,
        unlocks_units=['Knight', 'Militia'],
        unlocks_buildings=[],
        advancement_level=3,
    ),
    'Compass': TechTemplate(
        name='Compass',
        cost=70,
        unlocks_units=['Crossbowman'],
        unlocks_buildings=['Observatory', 'Great Lighthouse'],
        advancement_level=3,
    ),
    'Physics': TechTemplate(
        name='Physics',
        cost=70,
        unlocks_buildings=['Windmill'],
        unlocks_units=['Trebuchet'],
        advancement_level=3,
    ),
    'Printing Press': TechTemplate(
        name='Printing Press',
        cost=75,
        unlocks_buildings=['Forbidden Palace', 'Paper Maker'],
        advancement_level=4,
    ),
    'Gunpowder': TechTemplate(
        name='Gunpowder',
        cost=90,
        unlocks_units=['Musketman'],
        unlocks_buildings=['Himeji Castle'],
        advancement_level=4,
    ),
    'Renaissance': TechTemplate(
        name='Renaissance',
        cost=0,
        advancement_level=999,
    ),
    'Metallurgy': TechTemplate(
        name='Metallurgy',
        cost=95,
        unlocks_units=['Cannon'],
        unlocks_buildings=['Forge'],
        advancement_level=4,
    ),
    'Architecture': TechTemplate(
        name='Architecture',
        cost=100,
        unlocks_buildings=['Notre Dame', 'Lumber Farm'],
        advancement_level=4,
    ),
    "Medicine": TechTemplate(
        name='Medicine',
        cost=110,
        unlocks_buildings=['Apothecary', 'Zoo'],
        advancement_level=5,
    ),
    'Economics': TechTemplate(
        name='Economics',
        cost=120,
        unlocks_buildings=['Caravansery', 'Porcelain Tower'],
        advancement_level=4,
    ),
    'Military Science': TechTemplate(
        name='Military Science',
        cost=130,
        unlocks_units=['Cavalry'],
        unlocks_buildings=['Brandenburg Gate'],
        advancement_level=5,
    ),
    'Rifling': TechTemplate(
        name='Rifling',
        cost=140,
        unlocks_units=['Rifleman'],
        unlocks_buildings=['Outpost'],
        advancement_level=5,
    ),
    'Industrialization': TechTemplate(
        name='Industrialization',
        cost=150,
        unlocks_buildings=['Factory'],
        unlocks_units=['Gatling Gun'],
        advancement_level=5,
    ),
    'Dynamite': TechTemplate(
        name='Dynamite',
        cost=170,
        unlocks_units=['Artillery'],
        unlocks_buildings=['Railroads'],
        advancement_level=6,
    ),
    'Radio': TechTemplate(
        name='Radio',
        cost=250,
        unlocks_units=['Infantry'],
        unlocks_buildings=['Stadium', 'Statue of Liberty'],
        advancement_level=6,
    ),
    'Combined Arms': TechTemplate(
        name='Combined Arms',
        cost=300,
        unlocks_units=['Tank'],
        unlocks_buildings=['Kremlin'],
        advancement_level=7,
    ),
    'Ballistics': TechTemplate(
        name='Ballistics',
        cost=400,
        unlocks_units=['Machine Gun', 'Bazooka'],
        advancement_level=7,
    ),
    'Mechanized Agriculture': TechTemplate(
        name='Mechanized Agriculture',
        cost=450,
        unlocks_buildings=['Industrial Farm', 'Fast Food Chains'],
        advancement_level=7,
    ),
    'Rocketry': TechTemplate(
        name='Rocketry',
        cost=500,
        unlocks_units=['Rocket Launcher'],
        unlocks_buildings=['Apollo Program'],
        advancement_level=8,
    ),
    'Computers': TechTemplate(
        name='Computers',
        cost=600,
        unlocks_buildings=['Internet'],
        advancement_level=8,
    ),
    'Nanotechnology': TechTemplate(
        name='Nanotechnology',
        cost=750,
        unlocks_units=['Nanoswarm'],
        advancement_level=9,
    ),     
    'Megarobotics': TechTemplate(
        name='Megarobotics',
        cost=1000,
        unlocks_units=['Giant Death Robot'],
        unlocks_buildings=['AGI'],
        advancement_level=9,
    ),
}