TECHS = {
    'Archery': {
        'name': 'Archery',
        'cost': 25,
        'unlocks_units': ['Archer'],
        'advancement_level': 1,
    },
    'Bronze Working': {
        'name': 'Bronze Working',
        'cost': 25,
        'unlocks_units': ['Spearman'],
        'advancement_level': 1,
    },
    'Pottery': {
        'name': 'Pottery',
        'cost': 20,
        'unlocks_buildings': ['Granary'],
        'advancement_level': 1,
    },
    'Code of Laws': {
        'name': 'Code of Laws',
        'cost': 20,
        'unlocks_buildings': ['Hanging Gardens'],
        'advancement_level': 1,
        'great_scientist_name': 'Hammurabi',
    },
    'Calendar': {
        'name': 'Calendar',
        'cost': 25,
        'unlocks_buildings': ['Temple of Artemis'],
        'advancement_level': 1,
    },
    'The Wheel': {
        'name': 'The Wheel',
        'cost': 35,
        'unlocks_units': ['Chariot'],
        'advancement_level': 1,
    },
    'Mining': {
        'name': 'Mining',
        'cost': 30,
        'unlocks_buildings': ['Mine'],
        'advancement_level': 1,
    },
    'Forestry': {
        'name': 'Forestry',
        'cost': 25,
        'advancement_level': 1,
        'unlocks_buildings': ['Lumber Mill'],
    },
    'Irrigation': {
        'name': 'Irrigation',
        'cost': 25,
        'unlocks_buildings': ['Plantation', 'Husbandry Center'],
        'advancement_level': 1,
    },
    'Writing': {
        'name': 'Writing',
        'cost': 30,
        'unlocks_buildings': ['Library', 'Great Library'],
        'advancement_level': 1,
        'great_scientist_name': 'Socrates',
    },
    'Masonry': {
        'name': 'Masonry',
        'cost': 30,
        'unlocks_units': ['Garrison'],
        'unlocks_buildings': ['Pyramids'],
        'advancement_level': 1,
    },
    'Mathematics': {
        'name': 'Mathematics',
        'cost': 50,
        'unlocks_units': ['Catapult'],
        'unlocks_buildings': ['Workshop'],
        'advancement_level': 2,
        "great_scientist_name": "Euclid",
    },
    'Horseback Riding': {
        'name': 'Horseback Riding',
        'cost': 50,
        'unlocks_units': ['Horseman', 'Horse Archer'],
        'advancement_level': 2,
    },
    'Iron Working': {
        'name': 'Iron Working',
        'cost': 45,
        'unlocks_units': ['Swordsman'],
        'unlocks_buildings': ['Colossus'],
        'advancement_level': 2,
    },
    'Currency': {
        'name': 'Currency',
        'cost': 40,
        'unlocks_buildings': ['Petra', 'Bazaar'],
        'advancement_level': 2,
    },
    'Engineering': {
        'name': 'Engineering',
        'cost': 45,
        'unlocks_buildings': ['Timberworks',  'Statue of Zeus'],
        'advancement_level': 2,
    },
    'Construction': {
        'name': 'Construction',
        'cost': 50,
        'unlocks_buildings': ['Aqueduct', 'Colosseum'],
        'advancement_level': 2,
    },
    'Education': {
        'name': 'Education',
        'cost': 55,
        'unlocks_buildings': ['University', 'National College'],
        'advancement_level': 3,
    },
    'Machinery': {
        'name': 'Machinery',
        'cost': 60,
        'unlocks_units': [],
        'unlocks_buildings': ['Ironworks'],
        'advancement_level': 3,
    },
    'Civil Service': {
        'name': 'Civil Service',
        'cost': 60,
        'unlocks_buildings': ['Chichen Itza'],
        'unlocks_units': ['Pikeman'],
        'advancement_level': 3,
    },
    'Chivalry': {
        'name': 'Chivalry',
        'cost': 65,
        'unlocks_units': ['Knight', 'Militia'],
        'unlocks_buildings': [],
        'advancement_level': 3,
    },
    'Compass': {
        'name': 'Compass',
        'cost': 70,
        'unlocks_units': ['Crossbowman'],
        'unlocks_buildings': ['Observatory', 'Great Lighthouse'],
        'advancement_level': 3,
        'great_scientist_name': 'Galileo Galilei',
    },
    'Physics': {
        'name': 'Physics',
        'cost': 70,
        'unlocks_buildings': ['Windmill'],
        'unlocks_units': ['Trebuchet'],
        'advancement_level': 3,
        'great_scientist_name': 'Isaac Newton',
    },
    'Printing Press': {
        'name': 'Printing Press',
        'cost': 75,
        'unlocks_buildings': ['Forbidden Palace', 'Paper Maker'],
        'advancement_level': 4,
        'great_scientist_name': 'Johannes Gutenberg',
    },
    'Gunpowder': {
        'name': 'Gunpowder',
        'cost': 90,
        'unlocks_units': ['Musketman'],
        'unlocks_buildings': ['Himeji Castle'],
        'advancement_level': 4,
    },
    'Renaissance': {
        'name': 'Renaissance',
        'cost': 0,
        'advancement_level': 999,
    },
    'Metallurgy': {
        'name': 'Metallurgy',
        'cost': 95,
        'unlocks_units': ['Cannon'],
        'unlocks_buildings': ['Forge'],
        'advancement_level': 4,
    },
    'Architecture': {
        'name': 'Architecture',
        'cost': 100,
        'unlocks_buildings': ['Notre Dame', 'Lumber Farm'],
        'advancement_level': 4,
        'great_scientist_name': 'Michelangelo',
    },
    "Medicine": {
        'name': 'Medicine',
        'cost': 110,
        'unlocks_buildings': ['Apothecary', 'Zoo'],
        'advancement_level': 5,
        'great_scientist_name': 'Louis Pasteur',
    },
    'Economics': {
        'name': 'Economics',
        'cost': 120,
        'unlocks_buildings': ['Caravansery', 'Porcelain Tower'],
        'advancement_level': 4,
        'great_scientist_name': 'Adam Smith',
    },
    'Military Science': {
        'name': 'Military Science',
        'cost': 130,
        'unlocks_units': ['Cavalry'],
        'unlocks_buildings': ['Brandenburg Gate'],
        'advancement_level': 5,
    },
    'Rifling': {
        'name': 'Rifling',
        'cost': 140,
        'unlocks_units': ['Rifleman'],
        'unlocks_buildings': ['Outpost'],
        'advancement_level': 5,
    },
    'Industrialization': {
        'name': 'Industrialization',
        'cost': 150,
        'unlocks_buildings': ['Factory'],
        'unlocks_units': ['Gatling Gun'],
        'advancement_level': 5,
        'great_scientist_name': 'James Watt',
    },
    'Dynamite': {
        'name': 'Dynamite',
        'cost': 170,
        'unlocks_units': ['Artillery'],
        'unlocks_buildings': [],
        'advancement_level': 6,
        'great_scientist_name': 'Alfred Nobel',
    },
    'Radio': {
        'name': 'Radio',
        'cost': 250,
        'unlocks_units': ['Infantry'],
        'unlocks_buildings': ['Stadium', 'Statue of Liberty'],
        'advancement_level': 6,
    },
    'Combined Arms': {
        'name': 'Combined Arms',
        'cost': 300,
        'unlocks_units': ['Tank'],
        'unlocks_buildings': ['Kremlin'],
        'advancement_level': 7,
    },
    'Ballistics': {
        'name': 'Ballistics',
        'cost': 400,
        'unlocks_units': ['Machine Gun', 'Bazooka'],
        'advancement_level': 7,
    },
    'Mechanized Agriculture': {
        'name': 'Mechanized Agriculture',
        'cost': 450,
        'unlocks_buildings': ['Industrial Farm', 'Fast Food Chains'],
        'advancement_level': 7,
        'great_scientist_name': 'Norman Borlaug',
    },
    'Rocketry': {
        'name': 'Rocketry',
        'cost': 500,
        'unlocks_units': ['Rocket Launcher'],
        'unlocks_buildings': ['Apollo Program'],
        'advancement_level': 8,
        'great_scientist_name': 'Marie Curie',
    },
    'Computers': {
        'name': 'Computers',
        'cost': 600,
        'unlocks_buildings': ['Internet'],
        'advancement_level': 8,
        'great_scientist_name': 'Alan Turing',
    },
    'Nanotechnology': {
        'name': 'Nanotechnology',
        'cost': 750,
        'unlocks_units': ['Nanoswarm'],
        'advancement_level': 9,
    },     
    'Megarobotics': {
        'name': 'Megarobotics',
        'cost': 1000,
        'unlocks_units': ['Giant Death Robot'],
        'unlocks_buildings': ['AGI'],
        'advancement_level': 9,
    },
}