TECHS = {
    'Archery': {
        'name': 'Archery',
        'cost': 10,
        'unlocks_units': ['Archer'],
        'advancement_level': 1,
    },
    'Bronze Working': {
        'name': 'Bronze Working',
        'cost': 10,
        'unlocks_units': ['Spearman'],
        'advancement_level': 1,
    },
    'Pottery': {
        'name': 'Pottery',
        'cost': 10,
        'unlocks_buildings': ['Granary'],
        'advancement_level': 1,
    },
    'Code of Laws': {
        'name': 'Code of Laws',
        'cost': 10,
        'unlocks_buildings': ['Hanging Gardens'],
        'advancement_level': 1,
    },
    'Calendar': {
        'name': 'Calendar',
        'cost': 10,
        'unlocks_buildings': ['Temple of Artemis'],
        'advancement_level': 1,
    },
    'Ceremonial Burial': {
        'name': 'Ceremonial Burial',
        'cost': 10,
        'unlocks_buildings': ['Mausoleum of Halicarnassus'],
        'advancement_level': 1,
    },
    'The Wheel': {
        'name': 'The Wheel',
        'cost': 15,
        'unlocks_units': ['Chariot'],
        'advancement_level': 1,
    },
    'Mining': {
        'name': 'Mining',
        'cost': 15,
        'unlocks_buildings': ['Mine'],
        'advancement_level': 1,
    },
    'Forestry': {
        'name': 'Forestry',
        'cost': 15,
        'advancement_level': 1,
        'unlocks_buildings': ['Lumber Mill'],
    },
    'Irrigation': {
        'name': 'Irrigation',
        'cost': 15,
        'unlocks_buildings': ['Plantation'],
        'advancement_level': 1,
    },
    'Writing': {
        'name': 'Writing',
        'cost': 15,
        'unlocks_buildings': ['Library', 'Great Library'],
        'advancement_level': 1,
    },
    'Masonry': {
        'name': 'Masonry',
        'cost': 20,
        'unlocks_units': ['Garrison'],
        'unlocks_buildings': ['Pyramids'],
        'advancement_level': 1,
    },
    'Mathematics': {
        'name': 'Mathematics',
        'cost': 20,
        'unlocks_units': ['Catapult'],
        'advancement_level': 2,
    },
    'Horseback Riding': {
        'name': 'Horseback Riding',
        'cost': 20,
        'unlocks_units': ['Horseman', 'Horse Archer'],
        'advancement_level': 2,
    },
    'Iron Working': {
        'name': 'Iron Working',
        'cost': 25,
        'unlocks_units': ['Swordsman'],
        'unlocks_buildings': ['Colossus'],
        'advancement_level': 2,
    },
    'Currency': {
        'name': 'Currency',
        'cost': 25,
        'unlocks_buildings': ['Petra', 'Statue of Zeus'],
        'advancement_level': 2,
    },
    'Engineering': {
        'name': 'Engineering',
        'cost': 25,
        'unlocks_buildings': ['Ironworks'],
        'advancement_level': 2,
    },
    'Construction': {
        'name': 'Construction',
        'cost': 25,
        'unlocks_buildings': ['Aqueduct', 'Colosseum'],
        'advancement_level': 2,
    },
    'Education': {
        'name': 'Education',
        'cost': 30,
        'unlocks_buildings': ['University', 'National College'],
        'advancement_level': 3,
    },
    'Machinery': {
        'name': 'Machinery',
        'cost': 30,
        'unlocks_units': ['Crossbowman'],
        'unlocks_buildings': ['Timberworks'],
        'advancement_level': 3,
    },
    'Civil Service': {
        'name': 'Civil Service',
        'cost': 30,
        'unlocks_buildings': ['Chichen Itza'],
        'unlocks_units': ['Pikeman'],
        'advancement_level': 3,
    },
    'Chivalry': {
        'name': 'Chivalry',
        'cost': 35,
        'unlocks_units': ['Knight', 'Militia'],
        'unlocks_buildings': ['Husbandry Center'],
        'advancement_level': 3,
    },
    'Compass': {
        'name': 'Compass',
        'cost': 35,
        'unlocks_buildings': ['Observatory', 'Great Lighthouse'],
        'advancement_level': 3,
    },
    'Printing Press': {
        'name': 'Printing Press',
        'cost': 40,
        'unlocks_buildings': ['Forbidden Palace', 'Paper Maker'],
        'advancement_level': 4,
    },
    'Gunpowder': {
        'name': 'Gunpowder',
        'cost': 40,
        'unlocks_units': ['Musketman'],
        'unlocks_buildings': ['Himeji Castle'],
        'advancement_level': 4,
    },
}