UNITS = {
    "Scout": {
        "name": "Scout",
        "building_name": None,
        "type": "military",
        "metal_cost": 5,
        "wood_cost": 0,
        "strength": 2,
        "movement": 2,
        "range": 1,
        "tags": [],
        "abilities": [],
    },
    "Warrior": {
        "name": "Warrior",
        "building_name": None,
        "type": "military",
        "metal_cost": 8,
        "wood_cost": 0,
        "strength": 6,
        "movement": 1,
        "range": 1,
        "tags": ["infantry"],
        "abilities": [],
    },
    "Slinger": {
        "name": "Slinger",
        "building_name": "Pebble Pile",
        "type": "military",
        "metal_cost": 5,
        "wood_cost": 5,
        "strength": 4,
        "movement": 1,
        "range": 1,
        "tags": ["ranged"],
        "prereq": None,
        "abilities": [],
    },    
    "Archer": {
        "name": "Archer",
        "building_name": "Bowyer",
        "type": "military",
        "metal_cost": 7,
        "wood_cost": 10,
        "strength": 7,
        "movement": 1,
        "range": 1,
        "tags": ["ranged"],
        "prereq": "Archery",
        "abilities": [],
    },
    "Spearman": {
        "name": "Spearman",
        "building_name": "Spear Lodge",
        "type": "military",
        "metal_cost": 7,
        "wood_cost": 10,
        "strength": 8,
        "movement": 1,
        "range": 1,
        "tags": ["infantry"],
        "prereq": "Bronze Working",
        "abilities": [{
            "name": "BonusAgainst",
            "numbers": ["mounted", 4],
        }],
    },
    "Chariot": {
        "name": "Chariot",
        "building_name": "Wheelwright",
        "type": "military",
        "metal_cost": 10,
        "wood_cost": 10,
        "strength": 10,
        "movement": 1,
        "range": 1,
        "prereq": "The Wheel",
        "tags": ["mounted"],
        "abilities": [{
            "name": "BonusAgainst",
            "numbers": ["ranged", 5],
        }],
    },
    "Garrison": {
        "name": "Garrison",
        "building_name": "Walls",
        "type": "military",
        "metal_cost": 8,
        "wood_cost": 2,
        "strength": 12,
        "movement": 0,
        "range": 1,
        "prereq": "Masonry",
        "tags": ["defensive"],
        "abilities": [],
    },
    "Catapult": {
        "name": "Catapult",
        "building_name": "Siege Workshop",
        "type": "military",
        "metal_cost": 12,
        "wood_cost": 15,
        "strength": 8,
        "movement": 1,
        "range": 2,
        "tags": ["ranged", "siege"],
        "prereq": "Mathematics",
        "abilities": [{
            "name": "BonusNextTo",
            "numbers": ["infantry", 4],
        }],
    },
    "Horseman": {
        "name": "Horseman",
        "building_name": "Stable",
        "type": "military",
        "metal_cost": 12,
        "wood_cost": 15,
        "strength": 12,
        "movement": 2,
        "range": 1,
        "tags": ["mounted"],
        "prereq": "Horseback Riding",
        "abilities": [{
            "name": "BonusAgainst",
            "numbers": ["siege", 6],
        }],
    },
    "Horse Archer": {
        "name": "Horse Archer",
        "building_name": "Ranged Stable",
        "type": "military",
        "metal_cost": 15,
        "wood_cost": 20,
        "strength": 10,
        "movement": 2,
        "range": 1,
        "tags": ["ranged", "mounted"],
        "prereq": "Horseback Riding",
        "abilities": [{
            "name": "BonusAgainst",
            "numbers": ["infantry", 5],
        }],
    },
    "Swordsman": {
        "name": "Swordsman",
        "building_name": "Smithy",
        "type": "military",
        "metal_cost": 16,
        "wood_cost": 16,
        "strength": 16,
        "movement": 1,
        "range": 1,
        "tags": ["infantry"],
        "prereq": "Iron Working",
        "abilities": [],
    },
    "Pikeman": {
        "name": "Pikeman",
        "building_name": "Pikesmith",
        "type": "military",
        "metal_cost": 12,
        "wood_cost": 20,
        "strength": 14,
        "movement": 1,
        "range": 1,
        "tags": ["infantry"],
        "prereq": "Civil Service",
        "abilities": [{
            "name": "BonusAgainst",
            "numbers": ["mounted", 7],
        }],
    },
    "Crossbowman": {
        "name": "Crossbowman",
        "building_name": "Crossbow Range",
        "type": "military",
        "metal_cost": 15,
        "wood_cost": 20,
        "strength": 14,
        "movement": 1,
        "range": 1,
        "tags": ["ranged"],
        "prereq": "Machinery",
        "abilities": [{
            "name": "BonusNextTo",
            "numbers": ["siege", 4],
        }],
    },
    "Knight": {
        "name": "Knight",
        "building_name": "Tournament Grounds",
        "type": "military",
        "metal_cost": 25,
        "wood_cost": 20,
        "strength": 16,
        "movement": 3,
        "range": 1,
        "tags": ["mounted"],
        "prereq": "Chivalry",
        "abilities": [{
            "name": "BonusAgainst",
            "numbers": ["ranged", 8],
        }],
    },
    "Trebuchet": {
        "name": "Trebuchet",
        "building_name": "Adv. Siege Workshop",
        "type": "military",
        "metal_cost": 20,
        "wood_cost": 25,
        "strength": 12,
        "movement": 1,
        "range": 2,
        "tags": ["siege"],
        "prereq": "Physics",
        "abilities": [{
            "name": "BonusNextTo",
            "numbers": ["infantry", 6],
        }],
    },
    "Musketman": {
        "name": "Musketman",
        "building_name": "Gunsmith",
        "type": "military",
        "metal_cost": 15,
        "wood_cost": 25,
        "strength": 20,
        "movement": 1,
        "range": 1,
        "tags": ["infantry"],
        "prereq": "Gunpowder",
        "abilities": [],
    },
}

UNITS_BY_BUILDING_NAME = {
    unit_json["building_name"]: unit_json for unit_json in UNITS.values() if unit_json["building_name"] is not None
}

PRODUCTION_BUILDINGS_BY_UNIT_NAME = {
    unit_json["name"]: unit_json["building_name"] for unit_json in UNITS.values() if unit_json["building_name"] is not None
}