"""Add is_bot to players

Revision ID: 05a0b3b87180
Revises: 7d1b7f8df7db
Create Date: 2024-02-04 16:34:34.789000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05a0b3b87180'
down_revision = '7d1b7f8df7db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('animation_frame_idx_game_player_num_frame_num_turn_num', 'animation_frames', ['game_id', 'player_num', 'frame_num', 'turn_num'], unique=False)
    op.add_column('players', sa.Column('is_bot', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'is_bot')
    op.drop_index('animation_frame_idx_game_player_num_frame_num_turn_num', table_name='animation_frames')
    # ### end Alembic commands ###
