"""Add players

Revision ID: 161def1b4bb2
Revises: 7c984124eaf3
Create Date: 2023-11-05 14:56:29.727499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '161def1b4bb2'
down_revision = '7c984124eaf3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('player_num', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_created_at'), 'players', ['created_at'], unique=False)
    op.create_index('player_idx_game_player_num', 'players', ['game_id', 'player_num'], unique=True)
    op.create_index('player_idx_user_game', 'players', ['user_id', 'game_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('player_idx_user_game', table_name='players')
    op.drop_index('player_idx_game_player_num', table_name='players')
    op.drop_index(op.f('ix_players_created_at'), table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###
