"""Add animations_frames

Revision ID: 19d40f08eb17
Revises: 161def1b4bb2
Create Date: 2023-11-05 14:57:49.269409

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '19d40f08eb17'
down_revision = '161def1b4bb2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animation_frames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=True),
    sa.Column('turn_num', sa.Integer(), nullable=False),
    sa.Column('player_num', sa.Integer(), nullable=True),
    sa.Column('frame_num', sa.Integer(), nullable=False),
    sa.Column('game_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('animation_frame_idx_game_turn_num_player_num_frame_num', 'animation_frames', ['game_id', 'turn_num', 'player_num', 'frame_num'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('animation_frame_idx_game_turn_num_player_num_frame_num', table_name='animation_frames')
    op.drop_table('animation_frames')
    # ### end Alembic commands ###
