"""Add map_size and launched to games

Revision ID: 1c7522340b43
Revises: 19d40f08eb17
Create Date: 2023-11-06 18:25:22.273174

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1c7522340b43'
down_revision = '19d40f08eb17'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animation_frames', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('games', sa.Column('map_size', sa.Integer(), nullable=False))
    op.add_column('games', sa.Column('launched', sa.Boolean(), server_default='f', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'launched')
    op.drop_column('games', 'map_size')
    op.drop_column('animation_frames', 'data')
    # ### end Alembic commands ###
