"""Add seconds_per_turn to games

Revision ID: b24e69490762
Revises: 05a0b3b87180
Create Date: 2024-02-14 18:47:04.758577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b24e69490762'
down_revision = '05a0b3b87180'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('seconds_per_turn', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'seconds_per_turn')
    # ### end Alembic commands ###
