"""vitality_multiplier

Revision ID: b9267780d41f
Revises: c20dd9e831bd
Create Date: 2024-07-26 15:08:11.204648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9267780d41f'
down_revision = 'c20dd9e831bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('vitality_multiplier', sa.Float(), server_default='1.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'vitality_multiplier')
    # ### end Alembic commands ###
