"""game timer refactor

Revision ID: c20dd9e831bd
Revises: a94b53372924
Create Date: 2024-03-21 21:42:53.510069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c20dd9e831bd'
down_revision = 'a94b53372924'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Explicitly create the enum type in PostgreSQL
    timerstatus_type = sa.Enum('NORMAL', 'OVERTIME', 'PAUSED', name='timerstatus')
    timerstatus_type.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('game_over', sa.Boolean(), server_default='f', nullable=False))
    op.add_column('games', sa.Column('timer_status', sa.Enum('NORMAL', 'OVERTIME', 'PAUSED', name='timerstatus'), server_default='NORMAL', nullable=False))
    op.add_column('games', sa.Column('turn_num', sa.Integer(), server_default='1', nullable=False))
    op.add_column('games', sa.Column('next_forced_roll_at', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'next_forced_roll_at')
    op.drop_column('games', 'turn_num')
    op.drop_column('games', 'timer_status')
    op.drop_column('games', 'game_over')
    # ### end Alembic commands ###

    # Explicitly drop the enum type in PostgreSQL
    # Note: Be cautious with dropping types if they might be used elsewhere in your database
    sa.Enum(name='timerstatus').drop(op.get_bind(), checkfirst=True)
